In [2]:
!git clone https://github.com/felipeediez/proyecto_2.git
%cd proyecto_2

fatal: destination path 'proyecto_2' already exists and is not an empty directory.
/content/proyecto_2

Cargue los datos de energía del archivo `assets/Energy Indicators.xls`, que es una lista de indicadores de [suministro de energía y producción de electricidad renovable](assets/Energy%20Indicators.xls) de las [Naciones Unidas](https://unstats.un.org/unsd/environment/excel_file_tables/2013/Energy%20Indicators.xls) para el año 2013, y asigna esos datos a un DataFrame con el nombre de variable **energy**.
Ten en cuenta que este es un archivo de Excel y no un archivo de valores separados por comas (.csv). Además, asegúrate de excluir la información del pie de página y del encabezado del archivo de datos. Las primeras dos columnas son innecesarias, por lo que debes deshacerse de ellas. También debes cambiar las etiquetas de las columnas

In [116]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

file_name = '/content/proyecto_2/assets/Energy Indicators.xls'
energy = pd.read_excel (file_name, header = None, skiprows=18, skipfooter= 38)  # Leo el archivo .xls con pd.read_excel. Al leerlo le exigo que no contenga encabezados, que omita las primeras 18 filas y las ultimas 38.

energy = energy.drop (energy.columns [[0,1]], axis =1)  # Utilizo el método drop para eliminar las columnas seleccionadas [0,1], el argumento 'axis=1' indica que se estan eliminando columnas.

columns_names = ['Country', 'Energy Supply', 'Energy supply per Capita', '% Renewable']  # Establezo el nuevo nombre de las columnas.
energy.columns = columns_names  # Agrego los nombres nuevos a cada columna

Convierta `Energy Supply` a gigajulios (**Nota: hay 1,000,000 giga julios en un petajulio**). Para todos los países que carezcan de datos (por ejemplo, datos con \"...\"), asegúrese de que estos reflejen valores `np.NaN`.

In [ ]:
energy ['Energy Supply'].replace ('...', np.nan, inplace = True)  # Establezco que los elementos en la columna 'Energy Supply' que sean iguales a '...' sean modificados por np.nan, que representa un valor faltante en Pandas. Utilizo 'inplace=True' para que los cambios se realicen en el DataFrame 'energy' directamente.
energy ['Energy Supply'] *= 1000000  # Cada elemento de la columna 'Energy Supply' es multiplicado por 1000000 (1 petajulio = 1,000,000 gigajulio)

Cambia el nombre de los siguientes países según listado. También hay varios países que contienen paréntesis y numeros en su nombre. Asegúrete de eliminarlos.

In [118]:
name_change = {
    "Republic of Korea": "South Korea",
    "United States of America20" : "United States",
    "United Kingdom of Great Britain and Northern Ireland19": "United Kingdom",
    "China, Hong Kong Special Administrative Region": "Hong Kong"
  }  # Diccionrio que contiene los cambios de nombres

energy ['Country'] = energy ['Country'].replace (name_change)  # Especifico que los cambios contenidos en el diccionario name_change se deben realizar en la columna 'Country'
energy = energy.sort_values (by = 'Country', ascending = True)  # Ordeno la columna 'Country' alfabeticamente (para eso sirve el ascending)
energy ['Country'] = energy ['Country'].str.replace (r'\s*\([^)]*\)', '', regex = True )  # Cambio los caracteres que siguen luego de cero o mas especios y un ( hasta un cierre de parentesis por un espacio vacio en cada elemento de la columna 'Country'
energy ['Country'] = energy ['Country'].str.replace(r'\d', '', regex = True)  # Cambio el digito que le sigue al nombre de un país por un espacio vacio
energy.head()

          Country  Energy Supply Energy supply per Capita  % Renewable
0     Afghanistan   3.210000e+08                       10    78.669280
1         Albania   1.020000e+08                       35   100.000000
2         Algeria   1.959000e+09                       51     0.551010
3  American Samoa            NaN                      ...     0.641026
4         Andorra   9.000000e+06                      121    88.695650

A continuación, carga los datos del GDP (PBI) del archivo `assets/world_bank.csv`. Este es un archivo .csv del [Banco Mundial](https://data.worldbank.org/indicator/NY.GDP.MKTP.CD) que contiene el PBI de los países desde 1960 hasta 2015. Llame a este DataFrame **gdp**.
Asegúrete de omitir el encabezado y cambia el nombre de la  lista de países indicada.

In [119]:
gdp = pd.read_csv ('/content/proyecto_2/assets/world_bank.csv',skiprows=4, header = None)

new_name = {
    "Korea, Rep.": "South Korea",
    "Iran, Islamic Rep." : "Iran",
    "Hong Kong SAR, China": "Hong Kong"
  }  # Diccionario con los correspondientes cambios de nombres

gdp = gdp.replace ({0:new_name})  # Cambio los nombres de los paises al formato indicado
gdp.head()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
0,Country Name,Country Code,Indicator Name,Indicator Code,1960.0,1961.0,1962.0,1963.0,1964.0,1965.0,...,2.006000e+03,2.007000e+03,2.008000e+03,2.009000e+03,2.010000e+03,2.011000e+03,2.012000e+03,2.013000e+03,2.014000e+03,2.015000e+03
1,Aruba,ABW,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.467704e+09,NaN,NaN,NaN,NaN,NaN
2,Andorra,AND,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,4.018196e+09,4.021331e+09,3.675728e+09,3.535389e+09,3.346317e+09,3.185605e+09,3.129538e+09,3.127550e+09,NaN,NaN
3,Afghanistan,AFG,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,1.030523e+10,1.172119e+10,1.214448e+10,1.469733e+10,1.593680e+10,1.691113e+10,1.935220e+10,1.973134e+10,1.999032e+10,2.029415e+10
4,Angola,AGO,GDP at market prices (constant 2010 US$),NY.GDP.MKTP.KD,NaN,NaN,NaN,NaN,NaN,NaN,...,5.581103e+10,6.842044e+10,7.787420e+10,7.975320e+10,8.247091e+10,8.570262e+10,9.012096e+10,9.626143e+10,1.008863e+11,1.039106e+11

Finalmente, lee el [Sciamgo Journal and Country Rank data for Energy Engineering and Power Technology](https://www.scimagojr.com/countryrank.php?category=2102) desde el archivo `assets/scimagojr-3.xlsx`, que clasifica a los paises según sus contribuciones al área mencionada. Denomina este DataFrame con el nombre **sciamgo**.

In [ ]:
archivo = '/content/proyecto_2/assets/scimagojr-3.xlsx'
sciamgo = pd.read_excel (archivo)
sciamgo.head()

Creo un dataframe que contiene todas las filas, la columna 0 (serían el nombre de los paises) y las columnas desde la 50 a la 60 del dataframe **gdp**

In [ ]:
columnas_a_extraer = [0] + list(range(50, 60))  # Establezco las columnas a extraer. En este caso la 0, y de la columna 50 a la 60.
gdp_subset = gdp.iloc[:, columnas_a_extraer]  # Extraigo las columnas
gdp_subset.head()  # 2006 a 2016

Creo un dataframe que contiene los primeros 15 puestos de la columna '**Rank**' del dataframe **gdp**

In [ ]:
sciamgo_range = sciamgo [sciamgo['Rank'] <= 15]  # Extraigo las filas correspondientes a los paises que ocupan el ranking del 1 al 15
sciamgo_range

Genero una lista con los paises que deben estar incluidos junto con sus datos en el nuevo dataframe que una a los 3 anteriormente trabajados

In [100]:
selected_countries = sciamgo_range['Country'].tolist()  # Creo una lista que se desprende de los nombres de la anterior extracción de paises (ranking 1 a 15)
selected_countries.sort()  # Ordeno los nombres de los paises
selected_countries

['Australia',
 'Brazil',
 'Canada',
 'China',
 'France',
 'Germany',
 'India',
 'Iran',
 'Italy',
 'Japan',
 'Russian Federation',
 'South Korea',
 'Spain',
 'United Kingdom',
 'United States']

In [ ]:
gdp_subset_selected = gdp_subset[gdp_subset[0].isin(selected_countries)]   # Extraigo las filas de gdp_subset correspondientes a los países que están en la lista 'selected_countries'
gdp_subset_selected

In [ ]:
energy_selected = energy [energy['Country'].isin (selected_countries)] # Extraigo las filas de energy correspondientes a los países que están en la lista 'selected_countries'
energy_selected

Unifica los tres datasets: GDP, Energy, y ScimEn en un nuevo dataset (utilizando la intersección de los nombres de países). Utiliza solo los años del 2006 al 2015 de datos de GDP (PBI) y solo los 15 principales países según el ranking de Scimagojr 'Rank' (del 1 al 15). El índice de este DataFrame debe ser el nombre de los países, y las columnas deben ser ['Rank', 'Documents', 'Citable documents', 'Citations', 'Self-citations', 'Citations per document', 'H index', 'Energy Supply', 'Energy Supply per Capita', '% Renewable', '2006', '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015']. Esto debería devolver un DataFrame con 20 columnas y 15 entradas, y las filas del DataFrame deberían estar ordenadas por \"Rank\"

In [170]:
merged_df = pd.merge(sciamgo_range, gdp_subset_selected, how='inner', left_on='Country', right_on=0)  # Uno los dataframes 'sciamgo_range' y 'gdp_subset_selected' en un dataframe que solo contendrá las filas que tengan coincidencias en ambas tablas en función de las columnas clave especificadas ('Country' y '0')
merged_df = pd.merge(merged_df, energy_selected, how='inner', on='Country')  # Uno el anterior dataframe creado 'merged_df' con 'energy_selected' en un dataframe que solo contendrá las filas que tengan coincidencias en ambas tablas en función de las columnas clave especificadas ('Country' y '0')

merged_df = merged_df.set_index ('Country')  # Se establece como indice los elementos de la columna 'Country'
merged_df = merged_df.drop(0, axis=1)  # Se elimina la columna '0' donde estaban duplicados los nombres de los paises

new_n = {
    50: '2006',
    51: '2007',
    52: '2008',
    53: '2009',
    54: '2010',
    55: '2011',
    56: '2012',
    57: '2013',
    58: '2014',
    59: '2015'
}  # Diccionario que contiene las columnas a cambiar de nombre

merged_df = merged_df.rename(columns = new_n)  # Cambio el nombre de las columnas

merged_df.head ()

,Rank,Documents,Citable documents,Citations,Self-citations,Citations per document,H index,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,Energy Supply,Energy supply per Capita,% Renewable
Country,,,,,,,,,,,,,,,,,,,,
China,1,127050,126767,597237,411683,4.70,138,3.992331e+12,4.559041e+12,4.997775e+12,5.459247e+12,6.039659e+12,6.612490e+12,7.124978e+12,7.672448e+12,8.230121e+12,8.797999e+12,1.271910e+11,93,19.75491
United States,2,96661,94747,792274,265436,8.20,230,1.479230e+13,1.505540e+13,1.501149e+13,1.459484e+13,1.496437e+13,1.520402e+13,1.554216e+13,1.577367e+13,1.615662e+13,1.654857e+13,9.083800e+10,286,11.57098
Japan,3,30504,30287,223024,61554,7.31,134,5.496542e+12,5.617036e+12,5.558527e+12,5.251308e+12,5.498718e+12,5.473738e+12,5.569102e+12,5.644659e+12,5.642884e+12,5.669563e+12,1.898400e+10,149,10.23282
United Kingdom,4,20944,20357,206091,37874,9.84,139,2.419631e+12,2.482203e+12,2.470614e+12,2.367048e+12,2.403504e+12,2.450911e+12,2.479809e+12,2.533370e+12,2.605643e+12,2.666333e+12,7.920000e+09,124,10.60047
Russian Federation,5,18534,18301,34266,12422,1.85,57,1.385793e+12,1.504071e+12,1.583004e+12,1.459199e+12,1.524917e+12,1.589943e+12,1.645876e+12,1.666934e+12,1.678709e+12,1.616149e+12,3.070900e+10,214,17.28868

La pregunta anterior unió tres datasets y luego los redujo a las 15 entradas principales. Pero antes de reducirlos a los 15 elementos principales, ¿cuántas entradas se perdieron?



*   Esta función debería devolver un solo número

In [143]:
len_combined_df = len (energy) + len (gdp) + len (sciamgo)
len_merged_df = len (merged_df)

def lost_entries (len_merged_df, len_combined_df):
    lost_entries = len_combined_df - len (merged_df)
    return (f"Se perdieron {lost_entries} entradas.")

lost_entries (len_merged_df, len_combined_df)

'Se perdieron 668 entradas.'

¿Cuáles son los 15 países con mayor GDP (PBI) promedio en los últimos 10 años?

*   Esta función debería devolver una serie llamada `avgGDP` con 15 países y su GDP (PBI) promedio ordenado en orden descendente.

In [144]:
def avgGDP (merged_df):
    gdp_accumulated = merged_df.loc[:, '2006':'2015']  # Tomamos el dataframe con el ranking de 15 paises y con '.loc' seleccionamos todas las filas [':'] y las columnas desde '2006' hasta '2015'.
    mean = gdp_accumulated.mean(axis = 1)  # Luego se calcula el promedio  de las columnas seleccionadas para cada fila (en este caso, para cada país).
    avgGDP_sorted = mean.sort_values(ascending=True)  # Se ordena la serie en orden descendente

    return avgGDP_sorted

average_gdp = avgGDP (merged_df)
average_gdp

Country
Iran                  4.441558e+11
South Korea           1.106715e+12
Australia             1.164043e+12
Spain                 1.418078e+12
Russian Federation    1.565459e+12
Canada                1.660647e+12
India                 1.769297e+12
Italy                 2.120175e+12
Brazil                2.189794e+12
United Kingdom        2.487907e+12
France                2.681725e+12
Germany               3.493025e+12
Japan                 5.542208e+12
China                 6.348609e+12
United States         1.536434e+13
dtype: float64

¿Cuánto cambió el GDP (PBI) durante el lapso de 10 años para el país con el sexto GDP (PBI) promedio más grande?

*   Esta función debería devolver un solo número.

In [149]:
def change_of_gdp (average_gdp, merged_df):
      country_sixth_avgGDP = average_gdp.index[-6]
      gdp_2006 = merged_df.loc[country_sixth_avgGDP, '2006']
      gdp_2015 = merged_df.loc[country_sixth_avgGDP, '2015']
      change_gdp = gdp_2015 - gdp_2006

      return f"El cambio en el PBI durante 10 años para {country_sixth_avgGDP} fue de {change_gdp} puntos."

cambio_pbi = change_of_gdp (average_gdp, merged_df)
cambio_pbi

'El cambio en el PBI durante 10 años para United Kingdom fue de 246702696075.3999 puntos.'

¿Cuál es el suministro medio de energía per cápita (`Energy Supply per Capita`)?

*   Esta función debería devolver un solo número.

In [163]:
def energy_per_capita(merged_df):
    df = merged_df[merged_df['Energy supply per Capita'] != 0]
    energy_supply_mean = df['Energy supply per Capita'].mean()
    return f"El suministro medio de energía per cápita es de {energy_supply_mean}"

energy_per_capita(merged_df)

'El suministro medio de energía per cápita es de 157.6'

¿Qué país tiene el máximo `% Renewable` y cuál es el porcentaje?

*   Esta función debe devolver una tupla con el nombre del país y el porcentaje

In [169]:
def max_renewable (merged_df):
    df = merged_df [merged_df ['% Renewable'] != 0]
    max_percentage = df ['% Renewable'].max()
    max_index = df ['% Renewable'].idxmax()
    return max_index, max_percentage

max_renewable (merged_df)

('Brazil', 69.64803)

Cree una nueva columna que sea la relación entre `Self-Citations` y `Total Citations`.
¿Cuál es el valor máximo para esta nueva columna y qué país tiene la relación mas alta?

*   Esta función debe devolver una tupla con el nombre del país y el ratio (proporción).

In [177]:
def relation_columns (merged_df):
    merged_df ['Citation ratio'] = merged_df ['Self-citations'] / merged_df ['Citations']
    max_ratio = merged_df ['Citation ratio'].max ()
    max_index = merged_df ['Citation ratio'].idxmax()

    return max_index, max_ratio

relation_columns (merged_df)

('China', 0.6893126179389422)

Crea una columna que estime la población utilizando `Energy Supply` y `Energy Supply per capita`.
¿Cuál es el tercer país más poblado según esta estimación?

*   Esta función debería devolver el nombre del país

In [186]:
def population_density (merged_df):
    merged_df ['Population'] = merged_df ['Energy Supply'] / merged_df ['Energy supply per Capita']
    merged_df = merged_df.sort_values (by = 'Population', ascending = False)
    third_country = merged_df ['Population'].index[2]

    return third_country

population_density (merged_df)

'United States'

Crea una columna que estime el número de `Citable documents` por persona.¿Cuál es la correlación entre el número de `Citable documents` per cápita y el `Energy Supply per Capita`? Utiliza el método `.corr()`, (correlación de Pearson).

*   Esta función debería devolver un solo número.
*   (Opcional: utiliza la función `plot9()` para visualizar la relación entre el suministro de energía per cápita y los `Citable documents` per cápita)

In [ ]:
def plot9(merged_df):
    import matplotlib as plt
    %matplotlib inline

    top15 = merged_df
    top15['PopEst'] = top15['Energy Supply'] / top15['Energy Supply per Capita']
    top15['Citable docs per Capita'] = top15['Citable documents'] / top15['PopEst']
    top15.plot(x='Citable docs per Capita', y='Energy Supply per Capita', kind='scatter', xlim=[0, 0.0006])

plot9()

Crea una nueva columna con un valor igual a 1 si el valor de % de energía renovable del país (`% Renewable`) es igual o superior de la mediana de todos los países en el top 15, o con un valor igual a 0 si el valor de % de energía renovable del país (`% Renewable`) está por debajo de la mediana.

*   Esta función debería devolver una serie llamada `HighRenew` cuyo índice es el nombre del país ordenado ascendentemente según el ranking.

In [189]:
def new_column (merged_df):
    median_renewable= merged_df ['% Renewable'].median()  # Mediana de la columna '% Renewable'
    merged_df ['High Renew'] = merged_df ['% Renewable'] >= median_renewable  # True o False
    high_renew = merged_df ['High Renew'].astype(int)  # Pasamos los valores booleanos a 0 y 1 (int) y los guardamos en la variable
    return high_renew

new_column (merged_df)

Country
China                 1
United States         0
Japan                 0
United Kingdom        0
Russian Federation    1
Canada                1
Germany               1
India                 0
France                1
South Korea           0
Italy                 1
Spain                 1
Iran                  0
Australia             0
Brazil                1
Name: High Renew, dtype: int64

Utiliza el siguiente diccionario para agrupar los países por continente, luego crea un DataFrame que muestre el tamaño de la muestra (la cantidad de países en cada contenedor de continente) y la suma, la media y la desviación estándar para la población estimada de cada país.



*  Esta función debería devolver un DataFrame con un índice llamado Continent `['Asia', 'Australia', 'Europe', 'North America', 'South America']` y columnas `['size', 'sum', 'mean', 'std']`

In [208]:
import pandas as pd

# Diccionario de continentes
continent_dict = {
    'China': 'Asia',
    'United States': 'North America',
    'Japan': 'Asia',
    'United Kingdom': 'Europe',
    'Russian Federation': 'Europe',
    'Canada': 'North America',
    'Germany': 'Europe',
    'India': 'Asia',
    'France': 'Europe',
    'South Korea': 'Asia',
    'Italy': 'Europe',
    'Spain': 'Europe',
    'Iran': 'Asia',
    'Australia': 'Australia',
    'Brazil': 'South America'
}

merged_df['Continent'] = merged_df.index.map(continent_dict)  # Agrupo por continente y sumo la población de cada pais del continente
continent_summary = merged_df.groupby('Continent')['Population'].agg(size='count', sum='sum', mean = 'mean', std= 'std').reset_index()  # El método .agg() en Pandas se utiliza para realizar agregaciones en un DataFrame, osea que calcula una o más estadísticas sobre los datos en una o varias columnas.
continent_summary.set_index('Continent', inplace=True)  # Establecemos la columna 'Continent' como indice del dataframe
continent_summary.columns = ['Size', 'Sum', 'Mean', 'Std']  # Se renombran las columnas con los nombres indicados

continent_summary

               Size               Sum          Mean           Std
Continent
Asia              5   2898666386.6106  5.797333e+08  6.790979e+08
Australia         1   23316017.316017  2.331602e+07           NaN
Europe            6  457929667.216372  7.632161e+07  3.464767e+07
North America     2   352855249.48025  1.764276e+08  1.996696e+08
South America     1  205915254.237288  2.059153e+08           NaN